"""Shared Sage identity, configuration, and transport primitives."""

from .managed_authorizers import REQUIRED_DOOR_SCOPES, render_lane_authorizers
from .models import (
    TENANT_A,
    TENANT_B,
    AllowedTenantIssuerMap,
    ApiIssuerConfiguration,
    ManagedDoor,
    SourceSignalProofRecord,
    TargetCapabilityEvidence,
    TenantLaneConfiguration,
)
from .deployment_evidence import (
    HTTP_MCP_PASSTHROUGH_DOCUMENTATION_URL,
    JWT_PASSTHROUGH_DOCUMENTATION_URL,
    SourceSignalEvaluation,
    evaluate_source_signal_proof,
    record_target_capability_evidence,
    verify_target_capability_evidence,
)
from .cognito import (
    SAGE_SCOPE_PROFILE,
    AccessTokenCustomizerConfiguration,
    AuthorizedScopeGrant,
    customize_access_token,
    lambda_handler,
    load_access_token_customizer_configuration,
)
from .transport import (
    AUTHORIZATION_HEADER,
    CORRELATION_HEADER,
    REDACTED_AUTH_ARTIFACT,
    AuthenticationArtifact,
    AuthorizationTransport,
    CorrelationId,
    IdentityError,
    IdentityErrorCode,
    build_authorization_transport,
    build_correlation_headers,
    parse_bearer_authorization,
    serialize_identity_error,
    serialize_log_fields,
    serialize_safe_fields,
)

__all__ = [
    "REQUIRED_DOOR_SCOPES",
    "render_lane_authorizers",
    "TENANT_A",
    "TENANT_B",
    "AllowedTenantIssuerMap",
    "ApiIssuerConfiguration",
    "ManagedDoor",
    "SourceSignalProofRecord",
    "TargetCapabilityEvidence",
    "TenantLaneConfiguration",
    "HTTP_MCP_PASSTHROUGH_DOCUMENTATION_URL",
    "JWT_PASSTHROUGH_DOCUMENTATION_URL",
    "SourceSignalEvaluation",
    "evaluate_source_signal_proof",
    "record_target_capability_evidence",
    "verify_target_capability_evidence",
    "SAGE_SCOPE_PROFILE",
    "AccessTokenCustomizerConfiguration",
    "AuthorizedScopeGrant",
    "customize_access_token",
    "lambda_handler",
    "load_access_token_customizer_configuration",
    "AUTHORIZATION_HEADER",
    "CORRELATION_HEADER",
    "REDACTED_AUTH_ARTIFACT",
    "AuthenticationArtifact",
    "AuthorizationTransport",
    "CorrelationId",
    "IdentityError",
    "IdentityErrorCode",
    "build_authorization_transport",
    "build_correlation_headers",
    "parse_bearer_authorization",
    "serialize_identity_error",
    "serialize_log_fields",
    "serialize_safe_fields",
]
